export const nameTitles = { 'Categories': 'Categorías', 'Scales': 'Lista de Escalas' };
export const nameScales = [
   'Nutritional Assessment Short Form',
   'Índice de Barthel',
   'Escala de Lawton y Brody',
   'Yessavage',
   'Escala Gijon',
   'Escala Braden',
   'Cuestionario de Edimburgo',
   'SCORE',
   'Escala Framingham',
   'CAM',
   'Escala Has-bled',
   'Escala Padua',
   'Escala Caprini',
   'Índice de Comorbilidades de Charlson',
   'Mini-Mental State Examination',
   'Cuestionario CAGE',
   'Escala Morse',
];